### ISSUE TITLE
[kugo] ril reports errors for oem commands

### ISSUE THREAD

**Issue by oshmoun** [sonyxperiadev/transpower#3]
Seems transpower successfully detects device state and informs ril, only the latter returns an error, as seen in logcat -b radio:
05-09 13:40:44.230  2826  2826 E RILQ    : (0/2826): RIL[0][rild] qmi_ril_parse_oem_hook_header: Received un-handled/oem command id = 524489

**Comment by oshmoun** [comment]
ping @jzoran @jerpelea

**Comment by jzoran** [comment]
Looking into this.

**Comment by jerpelea** [comment]
those errors can be ignored
